{
  "history": [
    {
      "feedback": [
          "black",
          "black",
          "black"
      ],
      "guess": [
          "red",
          "red",
          "blue",
          "green"
      ]
    },
    {
      "feedback": [
          "black",
          "black"
      ],
      "guess": [
          "red",
          "red",
          "blue",
          "blue"
      ]
    }
  ]
}
